### ISSUE TITLE
Nie można dodać samego maila przy tworzeni org.

### ISSUE THREAD

**Issue by Byczax** [informatyzacja/strona-organizacji-studenckich#33]
Gdy kliknąłem dodaj maila z odznaczonym przyciskiem do samodzielnego uzupełniania, to mail się nie dodał, za to jak rozwinąłem pola do wypełnienia, pole do umieszczenia grafiki się świeciło na czerwono
![image](https://user-images.githubusercontent.com/61631855/219955681-4ce09b46-b101-4fdc-9e0c-9f0dd34b7ff4.png)

**Comment by Rei-x** [comment]
ciekawostka, dodawanie organizacji jeszcze nie działa, to tylko ui

**Comment by Byczax** [comment]
Ale coś czuję że to pole jest chyba zrobione jako obwiązkowe chociaż nie powinno

**Comment by Rei-x** [comment]
możliwe bardzo, jeszcze nie kombinowałem z tym
